server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
#    hibernate:
#      format_sql: true
#    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true #for initialization of resources/data.sql
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

baseUrl: http://localhost:8080/ #colocar por variavel de ambiente, dev e prod
#  'https://account_name.app.invoicexpress.com/clients/:client-id.json?api_key=YOUR%20API%20KEY%20HERE'