server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
#    hibernate:
#      format_sql: true
#    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true #for initialization of resources/data.sql
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
url:
  integrations:
    client: http://client:8081/client
    bahamasgov: http://bahamas-gov:8082/register